name: Main Tests

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v1
      with:
        java-version: 22
    - name: List directory
      id: test
      run: ls -R
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Run Tests
      run: mvn test
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
    - name: Send Telegram message on success
      if: success()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHATID }}
        token: ${{ secrets.BOTTOKEN }}
        message: "Все ок"
    - name: Send Telegram message on failure
      if: failure()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHATID }}
        token: ${{ secrets.BOTTOKEN }}
        message: "Тесты не пройдены. Подробности в отчете: https://github.com/${{ github.repository }}/commit/${{github.sha}}"
