name: Java CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v1
      with:
        java-version: 22
    - name: List directory
      id: test
      run: ls -R
      env:
        TRES: 'steps.test.outputs.test-result'
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
      env:
        TRES: 'ВСЕ ОК'
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHATID }}
        token: ${{ secrets.BOTTOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
            
          Repository: ${{ github.repository }}
          Test Results: ${{ env.TRES }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
