name: Test Workflow
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Run tests
      id: test
      run: |
        echo "List directory"
        ls -R
        echo "Build with Maven"
        mvn -B package --file pom.xml -DskipTests
        echo "Run tests with Maven"
        OUTPUT=$(mvn test)
        echo "::set-output name=test-result::$OUTPUT"

    - name: send telegram message on push
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHATID }}
        token: ${{ secrets.BOTTOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
            
          Repository: ${{ github.repository }}
          Test Results: ${{ steps.test.outputs.test-result }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
