name: Java CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v1
      with:
        java-version: 22
    - name: List directory
      run: ls -R
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: Send Telegram Message
        uses: s00d/fast-telegram-action@v9
        with:
          token: ${{ secrets.BOTTOKEN }}
          to: ${{ secrets.CHATID }}
          message: 'This is a test message from GitHub Actions!'
