name: Java CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v1
      with:
        java-version: 22
    - name: List directory
      id: test
      run: ls -R
    - name: Build with Maven
      run: mvn -B package --file pom.xml -e -X
      env:
        TRES: "steps.test.outputs.test-result"
    - name: Run Tests
      run: mvn test
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: success() || failure()
      with:
        report_paths: '**/target/surefire-reports/TEST-*.xml'
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHATID }}
        token: ${{ secrets.BOTTOKEN }}
        message: |
          Новый коммит от ${{ github.actor }} в репозитории ${{ github.repository }}:
          Комментарий: ${{ github.event.commits[0].message }}
            
          Результаты тестов: ${{ env.TRES }}
          Посмотреть изменения: https://github.com/${{ github.repository }}/commit/${{github.sha}}
      env:
        TRES: "ВСЕ ОК"
