name: Java CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v1
      with:
        java-version: 22
    - name: List directory
      run: ls -R
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: send telegram message on push
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHATID }}
        token: ${{ secrets.BOTTOKEN }}
        if: always()
        run: |
          MESSAGE="Все ок"
          if [ "${{ steps.Set up JDK 22.outcome }}" != "success" ] || [ "${{ steps.List directory.outcome }}" != "success" ] || [ "${{ steps.Build with Maven.outcome }}" != "success" ]; then
            MESSAGE="Ошибка"
          fi
          message: |
            ${{ github.actor }} внёс изменения в репозиторий: ${{ github.repository }}
            Комментарий к изменениям: ${{ github.event.commits[0].message }}
            
            Результат тестов: ${{ "$MESSAGE" }}  
            Посмотреть изменения: https://github.com/${{ github.repository }}/commit/${{github.sha}}
