name: Java CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v1
      with:
        java-version: 22
    - name: List directory
      run: ls -R
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: notification
      if: cancelled() == false
      uses: xinthink/action-telegram@v1.1
      with:
        botToken: ${{ secrets.BotToken }}
        jobStatus: ${{ job.status }}
